### ISSUE TITLE
AJAX doesn't work

### ISSUE THREAD

**Issue by DigitalSismo** [splatcollision/shorthand.js#2]
Hi, 

I have downloaded the whole package including the demo.html page and the Ajax call ( #ajaxdemo>h2 should load 'chunk.html' into next div on click ) doesn't work (on local dev). I've added jquery in the head of the HTML but it doesn't work either. How come ? What did I miss to make it work ? 

Thanks much and best regards,

**Comment by splatcollision** [comment]
Hi - First thing I can think of is that you're just opening demo.html from the filesystem into your browser, instead of serving it up from a web server. Try hosting the files on your local machine's webserver and see if that helps!

**Comment by DigitalSismo** [comment]
Thanks :)
